version: '3.8'

services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules  
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

